In [1]:
import requests
import pandas as pd

## 出走表とタイムテーブル
朝9時までに用意想定.
 - 返却値
   - {"message": "OK", "data": {"timetable": json_data, "runtable": json_data}}

In [2]:
url = "https://172.192.40.114/data"

headers = {
    # 認証キー:当日データAPIを使う時は共通
    "api-key": "AI_Keiba_2026",
    # "Racecards" or "Odds"
    "type_of_data": "Racecards",
    # Racecardsのときは日付, OddsのときはYYYYMMDDJJRRを入力:JJは場所コード, RRはレース番号
    # 場所コード："札幌", "函館", "福島", "新潟", "東京", "中山", "中京", "京都", "阪神", "小倉"は順番に01, 02, ..., 10
    "id": "20260712"
}

In [3]:
# --- リクエスト送信 ---
# 形だけ証明書なのでverify=Falseにする: Warningは出るが無視でオッケー
response = requests.get(url, headers=headers, verify=False)

# --- 結果表示 ---
if response.status_code == 200:
    data = response.json()
    print("成功:", data["message"])
else:
    print(f"エラー: {response.status_code}")
    print(response.text)

成功: OK

C:\Users\Sano01\anaconda3\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.192.40.114'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [4]:
check = pd.DataFrame(data["data"]["timetable"])
check

    year  month  day place  race_num start_time  class_code  track_code
0   2026      7   12    函館         1      09:50           7          24
1   2026      7   12    函館         2      10:20           7          17
2   2026      7   12    函館         3      10:50           7          24
3   2026      7   12    函館         4      11:20           7          17
4   2026      7   12    函館         5      12:10          15          17
5   2026      7   12    函館         6      12:40           7          17
6   2026      7   12    函館         7      13:10          23          24
7   2026      7   12    函館         8      13:40          23          24
8   2026      7   12    函館         9      14:10          43          17
9   2026      7   12    函館        10      14:45          43          24
10  2026      7   12    函館        11      15:20         131          17
11  2026      7   12    函館        12      16:05          23          17
12  2026      7   12    福島         1      10:05           7          54
13  2026      7   12    福島         2      10:40           7          24
14  2026      7   12    福島         3      11:10           7          17
15  2026      7   12    福島         4      11:40          15          17
16  2026      7   12    福島         5      12:30          15          17
17  2026      7   12    福島         6      13:01           7          24
18  2026      7   12    福島         7      13:30           7          17
19  2026      7   12    福島         8      14:00          23          17
20  2026      7   12    福島         9      14:35          23          17
21  2026      7   12    福島        10      15:10          67          24
22  2026      7   12    福島        11      15:45         163          17
23  2026      7   12    福島        12      16:30          43          24
24  2026      7   12    小倉         1      09:55           7          17
25  2026      7   12    小倉         2      10:30           7          24
26  2026      7   12    小倉         3      11:00           7          17
27  2026      7   12    小倉         4      11:30           7          17
28  2026      7   12    小倉         5      12:20          15          17
29  2026      7   12    小倉         6      12:50          15          17
30  2026      7   12    小倉         7      13:20          23          24
31  2026      7   12    小倉         8      13:50          23          17
32  2026      7   12    小倉         9      14:20          43          24
33  2026      7   12    小倉        10      14:55          43          17
34  2026      7   12    小倉        11      15:30         131          24
35  2026      7   12    小倉        12      16:15          23          17

In [5]:
check = pd.DataFrame(data["data"]["runtable"])
check.head(11)

,place,race_num,horse_num,dist,horse,sex,age,jockey,loaf_weight,father,mother,id,waku_num,race_id
0,函館,1,1,1000,ニシノギャルズ,牝,3,横山琉人,55.0,セイウンコウセイ,フィールドボニータ,23100360,1,202607120201100101
1,函館,1,2,1000,クリコイーコ,牝,3,河原田菜,51.0,ディーマジェスティ,クリノフラゴナール,23100786,2,202607120201100102
2,函館,1,3,1000,トリアングルレディ,牝,3,長浜鴻緒,54.0,ダノンバラード,プリンシプルレディ,23105161,3,202607120201100103
3,函館,1,4,1000,ビタミンドロップ,牡,3,丹内祐次,57.0,エスポワールシチー,リアンローズ,23105630,4,202607120201100104
4,函館,1,5,1000,ヒューザー,牡,3,古川奈穂,55.0,ヘニーヒューズ,サウスクイーン,23104180,5,202607120201100105
5,函館,1,6,1000,スイーヴル,牝,3,武豊,55.0,タワーオブロンドン,オトヒメ2,23101660,5,202607120201100106
6,函館,1,7,1000,マーゴットオネイロ,牡,3,横山武史,57.0,ゴールドドリーム,デイトユアドリーム,23105310,6,202607120201100107
7,函館,1,8,1000,アジーザム,牝,3,北村友一,55.0,ドレフォン,ミッキーバディーラ,23102951,6,202607120201100108
8,函館,1,9,1000,ホワイトラバーズ,牝,3,古川吉洋,55.0,ディーマジェスティ,ホッコーエレノア,23101742,7,202607120201100109
9,函館,1,10,1000,スプリングドリーム,牝,3,黛弘人,55.0,モズアスコット,ゴールドゲッコー,23106782,7,202607120201100110
10,函館,1,11,1000,ホウオウワイズ,牝,3,佐々木大,55.0,Bolt d'Oro,Oh Wise One,23107525,8,202607120201100111

## リアルタイムオッズ
発走時刻の4分30秒前にAPIサーバがJRA-VANから取得するので, その**少し後に実行**するようにしてください.
 - 返却値
   - {"message": "OK", "data": {"odds_rt": json_data}}

In [6]:
url = "https://172.192.40.114/data"

headers = {
    # 認証キー:当日データAPIを使う時は共通
    "api-key": "AI_Keiba_2026",
    # "Racecards" or "Odds"
    "type_of_data": "Odds",
    # Racecardsのときは日付, OddsのときはYYYYMMDDJJRRを入力:JJは場所コード, RRはレース番号
    # 場所コード："札幌", "函館", "福島", "新潟", "東京", "中山", "中京", "京都", "阪神", "小倉"は順番に01, 02, ..., 10
    "id": "202607120301"
}

In [7]:
# --- リクエスト送信 ---
# 形だけ証明書なのでverify=Falseにする: Warningは出るが無視でオッケー
response = requests.get(url, headers=headers, verify=False)

# --- 結果表示 ---
if response.status_code == 200:
    data = response.json()
    print("成功:", data["message"])
else:
    print(f"エラー: {response.status_code}")
    print(response.text)

成功: OK

C:\Users\Sano01\anaconda3\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.192.40.114'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [8]:
check = pd.DataFrame(data["data"]["odds_rt"])
check

           race_id  odds_type    comb     odds
0     202607120301          1      01     21.0
1     202607120301          2      01      4.2
2     202607120301          1      02     16.1
3     202607120301          2      02      3.5
4     202607120301          1      03      3.2
...            ...        ...     ...      ...
2969  202607120301          8  141308   3935.8
2970  202607120301          8  141309  13634.9
2971  202607120301          8  141310   3155.1
2972  202607120301          8  141311   2579.5
2973  202607120301          8  141312  17353.5

[2974 rows x 4 columns]

## エラー例

In [9]:
######### 認証キー間違い
url = "https://172.192.40.114/data"

headers = {
    # 認証キー:当日データAPIを使う時は共通
    "api-key": "AI_Keiba_2025",
    # "Racecards" or "Odds"
    "type_of_data": "Odds",
    # Racecardsのときは日付, OddsのときはYYYYMMDDJJRRを入力:JJは場所コード, RRはレース番号
    # 場所コード："札幌", "函館", "福島", "新潟", "東京", "中山", "中京", "京都", "阪神", "小倉"は順番に01, 02, ..., 10
    "id": "202607120301"
}
response = requests.get(url, headers=headers, verify=False)

print(f"エラー: {response.status_code}")
print(response.text)

C:\Users\Sano01\anaconda3\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.192.40.114'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

エラー: 401
{"detail":"Unauthorized"}

In [10]:
######### type_of_dataの間違い
url = "https://172.192.40.114/data"

headers = {
    # 認証キー:当日データAPIを使う時は共通
    "api-key": "AI_Keiba_2026",
    # "Racecards" or "Odds"
    "type_of_data": "tekito",
    # Racecardsのときは日付, OddsのときはYYYYMMDDJJRRを入力:JJは場所コード, RRはレース番号
    # 場所コード："札幌", "函館", "福島", "新潟", "東京", "中山", "中京", "京都", "阪神", "小倉"は順番に01, 02, ..., 10
    "id": "202607120301"
}
response = requests.get(url, headers=headers, verify=False)

print(f"エラー: {response.status_code}")
print(response.text)

エラー: 200
{"message":"Type NG","data":[]}

C:\Users\Sano01\anaconda3\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.192.40.114'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [11]:
######### idの間違い or まだデータ未生成
# 内部ではファイルの存在確認を行っている
url = "https://172.192.40.114/data"

headers = {
    # 認証キー:当日データAPIを使う時は共通
    "api-key": "AI_Keiba_2026",
    # "Racecards" or "Odds"
    "type_of_data": "Racecards",
    # Racecardsのときは日付, OddsのときはYYYYMMDDJJRRを入力:JJは場所コード, RRはレース番号
    # 場所コード："札幌", "函館", "福島", "新潟", "東京", "中山", "中京", "京都", "阪神", "小倉"は順番に01, 02, ..., 10
    "id": "20260832"
}
response = requests.get(url, headers=headers, verify=False)

print(f"エラー: {response.status_code}")
print(response.text)

C:\Users\Sano01\anaconda3\lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.192.40.114'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

エラー: 200
{"message":"Data None","data":[]}